# How to run this program
First, please make sure that you have **python3** installed (preferably **Anaconda** package).

Then use **jupyter notebook** to run the **.ipynb** file.

If you have any missing python modules, please install them using **pip install**.

In [181]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Loading data
Load the MovieLens data (educational version)

In [166]:
%%time
data_path = "ml-latest-small/ratings.csv"
data = pd.read_csv(data_path, sep=',', header=0)
data = data[['userId', 'movieId', 'rating']]

Wall time: 68.2 ms


In [148]:
data = data[:495]

In [170]:
user_ids = sorted(set(data['userId']))
movie_ids = sorted(set(data['movieId']))
n_users = len(user_ids)
n_movies = len(movie_ids)

print("Number of users: {}\nNumber of movies: {}".format(n_users, n_movies))

Number of users: 671
Number of movies: 9066


In [172]:
# show how many users have rated a certain movie
vector_sizes = data.groupby('movieId')['userId'].nunique().sort_values(ascending=False)
print(vector_sizes)
print('On average, each movie is rated {} times'.format(vector_sizes.mean()))

movieId
356       341
296       324
318       311
593       304
260       291
480       274
2571      259
1         247
527       244
589       237
1196      234
110       228
1270      226
608       224
1198      220
2858      220
780       218
1210      217
588       215
457       213
2959      202
590       202
47        201
50        201
4993      200
858       200
364       200
150       200
380       198
32        196
         ... 
26694       1
26695       1
26701       1
3003        1
26492       1
26346       1
3021        1
26349       1
26350       1
26371       1
26393       1
3031        1
26394       1
26400       1
3025        1
26404       1
26409       1
26413       1
26487       1
26414       1
26422       1
26430       1
26435       1
26462       1
26464       1
26467       1
26471       1
26480       1
26485       1
163949      1
Name: userId, dtype: int64
On average, each movie is rated 11.030664019413193 times


In [173]:
# show examples of the data
data

userId  movieId  rating
0            1       31     2.5
1            1     1029     3.0
2            1     1061     3.0
3            1     1129     2.0
4            1     1172     4.0
5            1     1263     2.0
6            1     1287     2.0
7            1     1293     2.0
8            1     1339     3.5
9            1     1343     2.0
10           1     1371     2.5
11           1     1405     1.0
12           1     1953     4.0
13           1     2105     4.0
14           1     2150     3.0
15           1     2193     2.0
16           1     2294     2.0
17           1     2455     2.5
18           1     2968     1.0
19           1     3671     3.0
20           2       10     4.0
21           2       17     5.0
22           2       39     5.0
23           2       47     4.0
24           2       50     4.0
25           2       52     3.0
26           2       62     3.0
27           2      110     4.0
28           2      144     3.0
29           2      150     5.0
...        ...      ...     ...
99974      671     4034     4.5
99975      671     4306     5.0
99976      671     4308     3.5
99977      671     4880     4.0
99978      671     4886     5.0
99979      671     4896     5.0
99980      671     4963     4.5
99981      671     4973     4.5
99982      671     4993     5.0
99983      671     4995     4.0
99984      671     5010     2.0
99985      671     5218     2.0
99986      671     5299     3.0
99987      671     5349     4.0
99988      671     5377     4.0
99989      671     5445     4.5
99990      671     5464     3.0
99991      671     5669     4.0
99992      671     5816     4.0
99993      671     5902     3.5
99994      671     5952     5.0
99995      671     5989     4.0
99996      671     5991     4.5
99997      671     5995     4.0
99998      671     6212     2.5
99999      671     6268     2.5
100000     671     6269     4.0
100001     671     6365     4.0
100002     671     6385     2.5
100003     671     6565     3.5

[100004 rows x 3 columns]

# Mean centering
Subtract mean of rating for each user

In [174]:
%%time
# find the mean of each user
user_group = data.groupby(by='userId')
user_means = user_group['rating'].agg(['mean', 'count'])

Wall time: 10 ms


In [175]:
# create a new column named "meanCenteredRating"

# this function takes in ratings of one user and return mean_centered ratings of that user
mean_centering = lambda ratings: ratings - ratings.mean()
data['meanCenteredRating'] = user_group['rating'].transform(mean_centering)
data

userId  movieId  rating  meanCenteredRating
0            1       31     2.5           -0.050000
1            1     1029     3.0            0.450000
2            1     1061     3.0            0.450000
3            1     1129     2.0           -0.550000
4            1     1172     4.0            1.450000
5            1     1263     2.0           -0.550000
6            1     1287     2.0           -0.550000
7            1     1293     2.0           -0.550000
8            1     1339     3.5            0.950000
9            1     1343     2.0           -0.550000
10           1     1371     2.5           -0.050000
11           1     1405     1.0           -1.550000
12           1     1953     4.0            1.450000
13           1     2105     4.0            1.450000
14           1     2150     3.0            0.450000
15           1     2193     2.0           -0.550000
16           1     2294     2.0           -0.550000
17           1     2455     2.5           -0.050000
18           1     2968     1.0           -1.550000
19           1     3671     3.0            0.450000
20           2       10     4.0            0.513158
21           2       17     5.0            1.513158
22           2       39     5.0            1.513158
23           2       47     4.0            0.513158
24           2       50     4.0            0.513158
25           2       52     3.0           -0.486842
26           2       62     3.0           -0.486842
27           2      110     4.0            0.513158
28           2      144     3.0           -0.486842
29           2      150     5.0            1.513158
...        ...      ...     ...                 ...
99974      671     4034     4.5            0.582609
99975      671     4306     5.0            1.082609
99976      671     4308     3.5           -0.417391
99977      671     4880     4.0            0.082609
99978      671     4886     5.0            1.082609
99979      671     4896     5.0            1.082609
99980      671     4963     4.5            0.582609
99981      671     4973     4.5            0.582609
99982      671     4993     5.0            1.082609
99983      671     4995     4.0            0.082609
99984      671     5010     2.0           -1.917391
99985      671     5218     2.0           -1.917391
99986      671     5299     3.0           -0.917391
99987      671     5349     4.0            0.082609
99988      671     5377     4.0            0.082609
99989      671     5445     4.5            0.582609
99990      671     5464     3.0           -0.917391
99991      671     5669     4.0            0.082609
99992      671     5816     4.0            0.082609
99993      671     5902     3.5           -0.417391
99994      671     5952     5.0            1.082609
99995      671     5989     4.0            0.082609
99996      671     5991     4.5            0.582609
99997      671     5995     4.0            0.082609
99998      671     6212     2.5           -1.417391
99999      671     6268     2.5           -1.417391
100000     671     6269     4.0            0.082609
100001     671     6365     4.0            0.082609
100002     671     6385     2.5           -1.417391
100003     671     6565     3.5           -0.417391

[100004 rows x 4 columns]

In [176]:
# show user means
user_means

mean  count
userId                 
1       2.550000     20
2       3.486842     76
3       3.568627     51
4       4.348039    204
5       3.910000    100
6       3.261364     44
7       3.465909     88
8       3.866379    116
9       3.755556     45
10      3.695652     46
11      4.078947     38
12      2.754098     61
13      3.745283     53
14      2.950000     20
15      2.621765   1700
16      4.120690     29
17      3.743802    363
18      3.235294     51
19      3.534279    423
20      3.290816     98
21      3.506173    162
22      3.275000    220
23      3.632920    726
24      3.666667     21
25      3.115385     26
26      3.468023    172
27      3.826087     23
28      4.280000     50
29      2.863636     22
30      3.765084   1011
...          ...    ...
642     3.916667     36
643     3.395833     24
644     3.743590     39
645     3.683333     30
646     4.130178    169
647     4.273333    150
648     3.628906    256
649     3.511111     90
650     3.310345     29
651     3.900000     20
652     4.220974    267
653     4.000000     51
654     4.068690    626
655     4.085714    105
656     4.523438    128
657     3.500000     20
658     4.350000     60
659     3.387324    142
660     4.168478     92
661     3.833333     33
662     3.396552     58
663     3.730769     26
664     3.796724    519
665     3.285714    434
666     2.950000     40
667     3.647059     68
668     3.750000     20
669     3.351351     37
670     3.806452     31
671     3.917391    115

[671 rows x 2 columns]

# Splitting data
Split the data into training set and test set. Prepare it as a user-item ratings matrix.

In [481]:
# randomly split the data set
test_size = 0.2
data_train, data_test = train_test_split(data, test_size=test_size, random_state=42)

# show shape of the data
data_train.shape, data_test.shape

((80003, 4), (20001, 4))

In [418]:
%%time
# build userId to row mapping dictionary
user2row = dict()
row2user = dict()
for i, user_id in enumerate(user_ids):
    user2row[user_id] = i
    row2user[i] = user_id

# build movieId to column mapping dictionary
movie2col = dict()
col2movie = dict()
for i, movie_id in enumerate(movie_ids):
    movie2col[movie_id] = i
    col2movie[i] = movie_id

Wall time: 958 ms


In [258]:
%%time
# turn ratings data in table format into a user-item rating matrix
# the field will be filled with NaN if user didn't provide a rating
def data_to_matrix(data):
    mat = np.full((n_users, n_movies), np.nan, dtype=np.float32)
    for idx, row in data.iterrows():
        mat[user2row[row['userId']], movie2col[row['movieId']]] = row['meanCenteredRating']
    return mat

# prepare the data as a user-item rating matrix for the next step
train_ratings = data_to_matrix(data_train)

Wall time: 4.26 s


# Compute similarity matrix
Build the item-item similarity matrix. This section takes most of the processing time.

In [273]:
# create a blank similarity matrix containing zeros
%time sim_matrix = np.zeros((n_movies, n_movies), dtype=np.float32)
sim_matrix.shape

Wall time: 2.98 ms


(9066, 9066)

In [254]:
# remove co-elements from 2 vectors if at least one of them is NaN
def remove_nans(a, b):
    # assuming that a and b are 1-d vectors, create a new axis for both of them
    a = a[..., np.newaxis]
    b = b[..., np.newaxis]
    concat = np.concatenate([a, b], axis=1)
    nonan = concat[~np.isnan(concat).any(axis=1)]
    return nonan[:, 0], nonan[:, 1]

# show examples of how to use remove_nans()
a = np.array([-1,2     ,np.nan,4])
b = np.array([-2,np.nan,3     ,5])
remove_nans(a, b)

(array([-1.,  4.]), array([-2.,  5.]))

In [311]:
# calculate a similarity value given 2 vectors
# the output is a value between -1 and 1
# min_co_elements is the number that determine whether to output NaN
# or output the similarity value, if co-elements are too low, the similarity
# will not be a good estimate, e.g. if there is only 1 co-element then the output
# will only be either -1 or 1, that's sometimes not desirable, so a threshold should be given
def calsim(item1, item2, min_co_elements=1):
    item1, item2 = remove_nans(item1, item2)
    if item1.size == 0 or item1.size < min_co_elements: # item1 and item2 must have the same size at this point
        return np.nan
#     print(item1.size)
    dot = item1.dot(item2)
    # find magnitude A.K.A. length of the vector by taking sqrt of the sum of squares of each element
    norm1 = np.linalg.norm(item1)
    norm2 = np.linalg.norm(item2)
    return dot / (norm1 * norm2)

# show example of how to use calsim()
calsim(a, b)

0.99083016804429913

In [328]:
%%time
# calculate all the similarities
for item1 in range(n_movies):
    item1vector = train_ratings[:, item1]
    for item2 in range(item1, n_movies):
        item2vector = train_ratings[:, item2]
        sim = calsim(item1vector, item2vector, min_co_elements=2)
        sim_matrix[item1, item2] = sim
        sim_matrix[item2, item1] = sim
    if (item1+1) % 50 == 0 or item1+1 == n_movies:
        print("Progress: {}/{} ({:.2f} %) items calculated".format(item1+1, n_movies, (item1+1)*100/n_movies))

Progress: 50/9066 (0.55 %) items calculated
Progress: 100/9066 (1.10 %) items calculated
Progress: 150/9066 (1.65 %) items calculated
Progress: 200/9066 (2.21 %) items calculated
Progress: 250/9066 (2.76 %) items calculated
Progress: 300/9066 (3.31 %) items calculated
Progress: 350/9066 (3.86 %) items calculated
Progress: 400/9066 (4.41 %) items calculated
Progress: 450/9066 (4.96 %) items calculated
Progress: 500/9066 (5.52 %) items calculated
Progress: 550/9066 (6.07 %) items calculated
Progress: 600/9066 (6.62 %) items calculated
Progress: 650/9066 (7.17 %) items calculated
Progress: 700/9066 (7.72 %) items calculated
Progress: 750/9066 (8.27 %) items calculated
Progress: 800/9066 (8.82 %) items calculated
Progress: 850/9066 (9.38 %) items calculated
Progress: 900/9066 (9.93 %) items calculated
Progress: 950/9066 (10.48 %) items calculated
Progress: 1000/9066 (11.03 %) items calculated
Progress: 1050/9066 (11.58 %) items calculated
Progress: 1100/9066 (12.13 %) items calculated
Prog

In [347]:
%%time
# this sim matrix takes a lot of time to compute,
# so saving it to the disk will help saving time in the future
np.save('sim_matrix', sim_matrix)

Wall time: 4.99 s


In [346]:
print('Fractions of similarity matrix that are NaN:', np.isnan(sim_matrix).mean())

Fractions of similarity matrix that are NaN: 0.936411215661


# Recommendation
Test recommendation using the item-item similarity matrix built previously.

1. We first need to define a predict() function then use it repeatedly to predict rating of every movie of a given user.
2. We then sort the predictions and show movies with top predictions

In [378]:
# define a predict function which receives row and column in the ratings matrix
# then output a rating value (without mean addition), or np.nan if there are no co-items
# user_item is a tuple (user_row, movie_column)
# sim_threshold is the similarity threshold of each item,
# if the item exceeds this value, it will be chosen for averaging the outcome
def predict(ratings, user_item, sim_threshold, debug=True):
    desired_user, desired_item = user_item
    rating_sum = 0.
    total_sim = 0.
    for item in range(ratings.shape[1]):
        s = sim_matrix[item, desired_item]
        rating = ratings[desired_user, item]
        if np.isnan(s) or s < sim_threshold or item == desired_item or np.isnan(rating):
            continue
        rating_sum += s * rating
        total_sim += s
        if debug:
            print('sim and rating of item {}:'.format(item), s, rating)
    return rating_sum / total_sim if total_sim else np.nan

In [483]:
# this is the similarity threshold value, as the only hyperparameter available
sim_threshold = 0.

In [382]:
predict(train_ratings, (0, 30), sim_threshold), train_ratings[0, 30]

sim and rating of item 906: 0.117642 -0.55
sim and rating of item 1017: 0.0505805 -0.55
sim and rating of item 1111: 0.815062 -0.05
sim and rating of item 1140: 0.0289128 -1.55
sim and rating of item 1665: 0.064384 1.45
sim and rating of item 1708: 0.550293 0.45
sim and rating of item 1815: 0.73969 -0.55
sim and rating of item 2925: 0.0604668 0.45


(-0.089294769241499483, -0.050000001)

In [444]:
# load the movie names
movie_file = "ml-latest-small/movies.csv"
movie_df = pd.read_csv(movie_file, header=0)
movie_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [473]:
# desired_user is the user row that we want to recommend
# return recommended item indices sorted by rating descendingly, and the associated score
def recommend(ratings, desired_user, sim_threshold):
    scores = []
    for item in range(ratings.shape[1]):
        score = ratings[desired_user, item]
        if np.isnan(score):
            score = predict(ratings, (desired_user, item), sim_threshold, debug=False)
        else:
            score = -np.infty # we don't want to recommend movies that user have rated
        scores.append(score)
    scores = np.array(scores)
    scores_argsort = np.argsort(scores)[::-1]
    scores_sort = np.sort(scores)[::-1]
    
    # numpy will put nan into the back of the array after sort
    # when we reverse the array, nan will be at the front
    # we want to move nan into the back again
    # so we use a numpy trick which rolls the array value
    # source: https://stackoverflow.com/a/35038821/2593810
    no_of_nan = np.count_nonzero(np.isnan(scores))
    scores_argsort = np.roll(scores_argsort, -no_of_nan)
    scores_sort = np.roll(scores_sort, -no_of_nan)
    return scores_argsort, scores_sort

def recommend_msg(user_row, scores_argsort, scores_sort, how_many=10):
    m = user_means.loc[row2user[user_row]]['mean']
    print('User mean rating:', m)
    msg = pd.DataFrame(columns=['movieId', 'title', 'genres', 'rating'])
    for i in range(how_many):
        col = scores_argsort[i]
        movie_id = col2movie[col]
        movie = movie_df.loc[movie_df['movieId'] == movie_id].iloc[0]
        msg.loc[i+1] = [movie_id, movie['title'], movie['genres'], scores_sort[i] + m]
    msg['movieId'] = msg['movieId'].astype(np.int32)
    return msg

In [434]:
%%time
user = 0 # the given user
scores_argsort, scores_sort = recommend(train_ratings, user, sim_threshold)

Wall time: 1min 51s


In [436]:
scores_argsort, scores_sort

(array([4880, 1387, 5743, ..., 6780, 6782,  563], dtype=int64),
 array([ 1.45000012,  1.45000012,  1.45000011, ...,         nan,
                nan,         nan]))

In [476]:
recommend_msg(user, scores_argsort, scores_sort, how_many=10)

User mean rating: 2.55


movieId                                         title  \
1      6951                    Cat in the Hat, The (2003)   
2      1769               Replacement Killers, The (1998)   
3     26231                            Performance (1970)   
4     36276          Hidden (a.k.a. Cache) (Caché) (2005)   
5      4443                                Outland (1981)   
6    139757                        Best of Enemies (2015)   
7      4570                       Big Picture, The (1989)   
8      3928  Abbott and Costello Meet Frankenstein (1948)   
9      1943            Greatest Show on Earth, The (1952)   
10     3181                                  Titus (1999)   

                    genres  rating  
1          Children|Comedy     4.0  
2    Action|Crime|Thriller     4.0  
3     Crime|Drama|Thriller     4.0  
4   Drama|Mystery|Thriller     4.0  
5   Action|Sci-Fi|Thriller     4.0  
6              Documentary     4.0  
7             Comedy|Drama     4.0  
8            Comedy|Horror     4.0  
9                    Drama     4.0  
10                   Drama     4.0

# Evaluation
Evaluate the error on the test set. The error metric chosen in our work is **MAE**.
1. We need to predict mean centered ratings of every (user,movie) pair in the test data
2. Take the difference between the true ratings and the predicted ratings
3. Take the absolute
4. Take the mean

And that's how the error is computed.

In [482]:
# first, let's take a look at some of the test data
data_test.head()

userId  movieId  rating  meanCenteredRating
19090     128     1028     5.0            1.139319
99678     665     4736     1.0           -2.285714
18455     120     4002     3.0           -0.485507
35755     257     1274     4.0            0.393204
66536     468     6440     4.0            1.034082

In [493]:
# predict ratings for the given data table
def predict_table(data_test, sim_threshold):
    n_test = data_test.shape[0]
    predictions = np.empty((n_test,))
    i = 0
    for idx, row in data_test.iterrows():
        pred = predict(train_ratings, (user2row[row['userId']], movie2col[row['movieId']]), sim_threshold, debug=False)
        predictions[i] = pred
        if (i+1) % 100 == 0 or i+1 == n_test:
            print("Progress: {}/{} ({:.2f} %) ratings predicted".format(i+1, n_test, (i+1)*100/n_test))
        i += 1
    print("Progress: {}/{} ({:.2f} %) ratings predicted".format(i+1, n_test, (i+1)*100/n_test))
    return predictions

In [492]:
%%time
# predicting ratings for every (user,movie) pair in the test data
predictions = predict_table(data_test, sim_threshold)

Progress: 100/20001 (0.50 %) ratings predicted
Progress: 200/20001 (1.00 %) ratings predicted
Progress: 300/20001 (1.50 %) ratings predicted
Progress: 400/20001 (2.00 %) ratings predicted
Progress: 500/20001 (2.50 %) ratings predicted
Progress: 600/20001 (3.00 %) ratings predicted
Progress: 700/20001 (3.50 %) ratings predicted
Progress: 800/20001 (4.00 %) ratings predicted
Progress: 900/20001 (4.50 %) ratings predicted
Progress: 1000/20001 (5.00 %) ratings predicted
Progress: 1100/20001 (5.50 %) ratings predicted
Progress: 1200/20001 (6.00 %) ratings predicted
Progress: 1300/20001 (6.50 %) ratings predicted
Progress: 1400/20001 (7.00 %) ratings predicted
Progress: 1500/20001 (7.50 %) ratings predicted
Progress: 1600/20001 (8.00 %) ratings predicted
Progress: 1700/20001 (8.50 %) ratings predicted
Progress: 1800/20001 (9.00 %) ratings predicted
Progress: 1900/20001 (9.50 %) ratings predicted
Progress: 2000/20001 (10.00 %) ratings predicted
Progress: 2100/20001 (10.50 %) ratings predicted

In [500]:
data_test['prediction'] = predictions
data_test.head()

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


userId  movieId  rating  meanCenteredRating  prediction
19090     128     1028     5.0            1.139319   -0.075033
99678     665     4736     1.0           -2.285714         NaN
18455     120     4002     3.0           -0.485507    0.090853
35755     257     1274     4.0            0.393204    0.329624
66536     468     6440     4.0            1.034082    0.169497

In [507]:
data_test['abs_error'] = np.abs(data_test['meanCenteredRating'] - data_test['prediction'])
data_test.head()

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


userId  movieId  rating  meanCenteredRating  prediction  abs_error
19090     128     1028     5.0            1.139319   -0.075033   1.214352
99678     665     4736     1.0           -2.285714         NaN        NaN
18455     120     4002     3.0           -0.485507    0.090853   0.576360
35755     257     1274     4.0            0.393204    0.329624   0.063580
66536     468     6440     4.0            1.034082    0.169497   0.864585

In [513]:
# mean absolute error
mae = data_test['abs_error'].mean()
mae

0.6850314415989894

Find the best set of hyperparameters that yields the lowest error on the test set.
In this work, we use **sim_threshold (similarity threshold)** as the only hyperparameter of the system.

We can find the best **sim_threshold** by iteratively
1. varying its value
2. predict outcome on the test set
3. evaluate the error
4. if the error is less than the least error found so far, save current **sim_threshold** as the best candidate

Repeat this cycle until enough satisfaction is achieved.

Plot the error as a function of **NN**.

# Inference on the Real World
This is the last step, all we have done to this point is now on production.

**Our task:** Given a user, recommend some movies.

In [104]:
# try finding similarity of all items vs the 5th item
# make sure to ignore the first row because we would like to predict the 5th item's first row
for i in range(ratings.shape[1]):
    s = sim(ratings[1:,4], ratings[1:,i])
    print(s)

0.9941
0.738851
0.72261
0.939558
1.0


In [106]:
# try finding similarity of all items vs the 5th and 6th item
# make sure to ignore the first row because we would like to predict the first row
item = 4
print('item', item)
for i in range(ratings2.shape[1]):
    s = sim(ratings2[1:,item], ratings2[1:,i])
    print(s)
item = 5
print('item', item)
for i in range(ratings2.shape[1]):
    s = sim(ratings2[1:,item], ratings2[1:,i])
    print(s)

item 4
0.877454
0.991315
0.910446
0.800044
1.0
0.778499
item 5
0.943701
0.783349
0.919709
0.981981
0.778499
1.0


In [107]:
# make sure that ratings is float array with nan values
def mean_ratings(ratings):
    return np.nanmean(ratings, axis=1, keepdims=True) # mean for each user
means = mean_ratings(ratings)
means2 = mean_ratings(ratings2)
means, means2

(array([[ 4.        ],
        [ 2.4000001 ],
        [ 3.79999995],
        [ 3.20000005],
        [ 2.79999995]], dtype=float32), array([[ 3.25      ],
        [ 2.75      ],
        [ 2.        ],
        [ 2.20000005],
        [ 2.16666675],
        [ 2.        ],
        [ 3.        ],
        [ 3.        ]], dtype=float32))

In [109]:
mean_adjusted_ratings = ratings - means
mean_adjusted_ratings2 = ratings2 - means2
mean_adjusted_ratings

array([[ 1.        , -1.        ,  0.        ,  0.        ,         nan],
       [ 0.5999999 , -1.4000001 , -0.4000001 ,  0.5999999 ,  0.5999999 ],
       [ 0.20000005, -0.79999995,  0.20000005, -0.79999995,  1.20000005],
       [-0.20000005, -0.20000005, -2.20000005,  1.79999995,  0.79999995],
       [-1.79999995,  2.20000005,  2.20000005, -0.79999995, -1.79999995]], dtype=float32)

In [110]:
mean_adjusted_ratings2

array([[ 1.75      , -1.25      , -0.25      , -0.25      ,         nan,
                nan],
       [-0.75      ,         nan,  1.25      ,         nan,  1.25      ,
        -1.75      ],
       [ 1.        , -1.        ,  1.        ,         nan, -1.        ,
         0.        ],
       [ 1.79999995, -0.20000005,  0.79999995, -1.20000005,         nan,
        -1.20000005],
       [ 0.83333325,  0.83333325, -0.16666675, -1.16666675,  0.83333325,
        -1.16666675],
       [        nan,  1.        ,         nan, -1.        ,  0.        ,
                nan],
       [ 1.        ,  0.        ,         nan,  0.        ,  0.        ,
        -1.        ],
       [        nan,  2.        ,         nan, -2.        ,  2.        ,
        -2.        ]], dtype=float32)

In [28]:
for i in range(ratings.shape[1]):
    s = sim(mean_adjusted_ratings[1:,4], mean_adjusted_ratings[1:,i])
    print(s)

0.804914
-0.908232
-0.76356
0.433063
1.0


In [111]:
item = 4
print('item', item)
for i in range(ratings.shape[1]):
    s = sim(mean_adjusted_ratings2[1:,item], mean_adjusted_ratings2[1:,i])
    print(s)
item = 5
print('item', item)
for i in range(ratings.shape[1]):
    s = sim(mean_adjusted_ratings2[1:,item], mean_adjusted_ratings2[1:,i])
    print(s)

item 4
-0.381663
0.922292
0.145844
-0.909896
1.0
item 5
-0.422256
-0.707524
-0.67853
0.933709
-0.865786


In [65]:
predict(ratings, 4, 0.8)

sim and rating item 0: 0.9941 5.0
sim and rating item 3: 0.939558 4.0


4.5141033336160996

In [66]:
predict(mean_adjusted_ratings, 4, 0.4)

sim and rating item 0: 0.804914 1.0
sim and rating item 3: 0.433063 0.0


0.65018527613807142

In [113]:
predict(mean_adjusted_ratings2, 4, 0.5), predict(mean_adjusted_ratings2, 5, 0.5)

sim and rating item 1: 0.922292 -1.25
sim and rating item 3: 0.933709 -0.25


(-1.2499999353733469, -0.25)

In [84]:
recommend(ratings), recommend(mean_adjusted_ratings)

((array([1, 4, 3, 2, 0], dtype=int64),
  array([ 3.6950829 ,  4.29723834,  3.92224987,  4.05011129,  4.07518138])),
 (array([2, 1, 3, 0, 4], dtype=int64),
  array([-0.74862116,  1.41862764,  1.52539193, -0.71216067, -3.94902346])))

In [118]:
recommend(ratings2), recommend(mean_adjusted_ratings2)

((array([1, 3, 2, 5, 4, 0], dtype=int64),
  array([ 2.65802582,  3.72206135,  3.35822932,  3.36198805,  3.21333831,
          3.30425242])),
 (array([4, 3, 1, 5, 0, 2], dtype=int64),
  array([-0.53560819, -0.02305332, -1.66111259,  0.11646881,  7.29449732,
         -0.0933717 ])))